# Generated by Django 6.0.7 on 2026-07-21 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VTUTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data')], max_length=16)),
                ('network', models.CharField(max_length=30)),
                ('subcategory_id', models.CharField(max_length=10)),
                ('plan_id', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=16)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('provider_ref', models.CharField(blank=True, max_length=64)),
                ('provider_response', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtu_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='vtu_vtutran_user_id_ebcbf7_idx'), models.Index(fields=['status'], name='vtu_vtutran_status_bdda7b_idx')],
            },
        ),
    ]
