# Generated by Django 6.0.7 on 2026-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtutransaction',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vtutransaction',
            name='service',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('cable', 'Cable TV'), ('electricity', 'Electricity')], max_length=16),
        ),
    ]
