# Generated by Django 6.0.7 on 2026-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_convert_crypto_deposits',
            field=models.BooleanField(default=False, help_text='Sell incoming on-chain crypto deposits to NGN at the live rate.'),
        ),
    ]
