# Generated by Django 6.0.7 on 2026-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flw_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flw_transfer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='virtual_account_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
