# Generated by Django 6.0.7 on 2026-07-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_deposit_method_transaction_flw_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deposit_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='flw_order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='flw_transfer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='virtual_account_expires_at',
        ),
    ]
