# Generated by Django 6.0.7 on 2026-07-23 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=4)),
                ('product_id', models.BigIntegerField()),
                ('product_name', models.CharField(blank=True, max_length=160)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('reloadly_tx_id', models.CharField(blank=True, max_length=32)),
                ('redeem_code', models.CharField(blank=True, max_length=120)),
                ('redeem_pin', models.CharField(blank=True, max_length=60)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='giftcards_g_user_id_5c22b8_idx'), models.Index(fields=['status'], name='giftcards_g_status_40a5b1_idx')],
            },
        ),
    ]
