# Generated by Django 6.0.7 on 2026-07-27 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitnob_card_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('bitnob_customer_id', models.CharField(blank=True, max_length=64)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('frozen', 'Frozen'), ('terminated', 'Terminated')], default='pending', max_length=12)),
                ('created_status', models.CharField(blank=True, max_length=16)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('masked_pan', models.CharField(blank=True, max_length=24)),
                ('cardholder_name', models.CharField(blank=True, max_length=150)),
                ('balance_usd_micro', models.CharField(default='0', max_length=32)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitnob_transaction_id', models.CharField(blank=True, max_length=64)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('funding', 'Funding'), ('withdrawal', 'Withdrawal')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('amount_usd_micro', models.CharField(max_length=32)),
                ('fee_usd_micro', models.CharField(blank=True, max_length=32)),
                ('ngn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.virtualcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cards.virtualcard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='virtualcard',
            index=models.Index(fields=['status'], name='cards_virtu_status_c2ab18_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['card', '-created_at'], name='cards_cardt_card_id_b2fb36_idx'),
        ),
    ]
