# Generated by Django 6.0.7 on 2026-07-26 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc_selfies/')),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='kyc_documents/')),
                ('dojah_reference_id', models.CharField(blank=True, max_length=64)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('review', 'Needs review')], default='pending', max_length=10)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC verification',
                'verbose_name_plural': 'KYC verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KycLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kyc.kycverification')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kycverification',
            index=models.Index(fields=['status'], name='kyc_kycveri_status_df6c85_idx'),
        ),
    ]
