# Generated by Django 6.0.7 on 2026-09-18 07:21

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='dojah_reference_id',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='reference_id',
            field=models.CharField(blank=True, default=kyc.models.generate_kyc_reference, max_length=64),
        ),
    ]
