# Generated by Django 6.0.7 on 2026-07-25 13:06

import crypto.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap')], max_length=8)),
                ('coin', models.CharField(max_length=10)),
                ('to_coin', models.CharField(blank=True, max_length=10)),
                ('coin_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('rate_ngn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('to_rate_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fee_ngn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_ngn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('to_coin_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=crypto.models._default_quote_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='crypto_cryp_user_id_045fdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('available', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('reserved', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'coin'), name='unique_crypto_wallet_per_coin')],
            },
        ),
    ]
