# Generated by Django 6.0.7 on 2026-07-25 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_cryptoquote_cryptowallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap')], max_length=8)),
                ('coin', models.CharField(max_length=10)),
                ('to_coin', models.CharField(blank=True, max_length=10)),
                ('coin_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('to_coin_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('rate_ngn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('to_rate_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fee_ngn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_ngn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_received', 'Payment received'), ('waiting_deposit', 'Waiting deposit'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_payment', max_length=20)),
                ('quidax_order_id', models.CharField(blank=True, max_length=64)),
                ('quidax_sell_order_id', models.CharField(blank=True, max_length=64)),
                ('deposit_address', models.CharField(blank=True, max_length=255)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='crypto_proofs/')),
                ('flw_tx_ref', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crypto.cryptoquote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crypto.cryptoorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cryptoorder',
            index=models.Index(fields=['user', '-created_at'], name='crypto_cryp_user_id_b31120_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoorder',
            index=models.Index(fields=['status'], name='crypto_cryp_status_7a6dc0_idx'),
        ),
    ]
