# Generated by Django 6.0.7 on 2026-07-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_cryptoorder_cryptoorderlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoorder',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crypto.cryptoquote'),
        ),
    ]
