# Generated by Django 6.0.7 on 2026-07-25 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_cryptodepositevent_quidaxsubaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('coin', models.CharField(max_length=10)),
                ('network', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('fee_coin', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('net_amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('rate_ngn', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='processing', max_length=16)),
                ('quidax_withdrawal_id', models.CharField(blank=True, max_length=64)),
                ('tx_id', models.CharField(blank=True, max_length=128)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoWithdrawalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crypto.cryptowithdrawal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cryptowithdrawal',
            index=models.Index(fields=['user', '-created_at'], name='crypto_cryp_user_id_b94a44_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowithdrawal',
            index=models.Index(fields=['status'], name='crypto_cryp_status_a34f0e_idx'),
        ),
    ]
