# Generated by Django 6.0.7 on 2026-10-08 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_cryptowithdrawal_cryptowithdrawallog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDepositSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('auto_convert', models.BooleanField(default=False)),
                ('reserved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending sweep'), ('sweeping', 'Sweeping'), ('swept', 'Swept to master'), ('selling', 'Selling'), ('completed', 'Completed'), ('skipped', 'Conversion skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('sweep_attempt', models.PositiveIntegerField(default=0)),
                ('sweep_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('quidax_sweep_id', models.CharField(blank=True, max_length=64)),
                ('swept_at', models.DateTimeField(blank=True, null=True)),
                ('step_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='crypto.cryptodepositevent')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crypto.cryptoorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposit_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoDepositSettlementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crypto.cryptodepositsettlement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cryptodepositsettlement',
            index=models.Index(fields=['status', 'next_attempt_at'], name='crypto_cryp_status_7f8e1a_idx'),
        ),
    ]
