# Generated by Django 6.0.7 on 2026-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_cryptodepositsettlement_cryptodepositsettlementlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoorder',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
