# Generated by Django 6.0.7 on 2026-10-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_cryptoorder_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoorder',
            name='fee_to_coin',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='gross_to_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='quidax_swap_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='quidax_swap_quotation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='swap_method',
            field=models.CharField(blank=True, choices=[('ngn_two_leg', 'Sell to NGN, then buy'), ('instant', 'Quidax Instant Swap')], max_length=16),
        ),
        migrations.AddField(
            model_name='cryptoquote',
            name='fee_to_coin',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='cryptoquote',
            name='gross_to_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='cryptoquote',
            name='swap_method',
            field=models.CharField(blank=True, choices=[('ngn_two_leg', 'Sell to NGN, then buy'), ('instant', 'Quidax Instant Swap')], max_length=16),
        ),
    ]
